#!/usr/bin/env bash
# displays numbers from 1 to 20.

c=1
while [ $c -lt 21 ]
do
	case $c in

 	 4)
		echo $c
		echo "bad luck from China"
		;;
	 9)
		echo $c
		echo "bad luck from Japan"
		;;
	 17)
		echo $c
		echo "bad luck from Italy"
		;;
	 *)
		echo $c
		;;
	esac
	let c+=1
done
