#!/usr/bin/env bash
# Bash script that creates an RSA key pair.
#Name of the created private key must be school
#The created key must be protected by the passphrase betty
# Generate RSA key pair with 4096 bits.
ssh-keygen -t rsa -b 4096 -P betty -f school
