#!/usr/bin/env bash
# Bash script that creates an RSA key pair.
# Generate RSA key pair with 4096 bits
openssl genpkey -algorithm RSA -out school.key -pkeyopt rsa_keygen_bits:4096

# Encrypt the private key with a passphrase
openssl rsa -in school.key -out school_encrypted.key -aes256 -passout pass:betty
