#!/usr/bin/env bash
# machine has an SSH configuration file for the local SSH client
#can connect to a server without typing a password.
  SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
